---
- name: configure the aliases
  template: src=alias.tpl dest=/root/.bash_aliases

- name: configure the timezone
  template: src=timezone.tpl dest=/etc/timezone
  notify: base_update_timezone

- locale_gen: name=de_DE state=present
- locale_gen: name=de_DE@euro state=present
- locale_gen: name=de_DE.UTF-8 state=present

- name: install ntp services
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ntp
    - ntpdate
  notify: base_update_ntp

- name: install packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - nano
    - htop
    - locate
    - curl
    - finger
    - software-properties-common
    - python-passlib
    - python-pip
    - nullmailer
    - git
    - subversion

- name: create mailname
  template: src=mailname.tpl dest=/etc/mailname

- name: create nullmailer remotes
  template: src=nullmailer/remotes.tpl dest=/etc/nullmailer/remotes