---
- name: create volume directory for container volume
  file: path=/opt/docker/mysql/data state=directory recurse=yes

- name: create volume directory for container configuration
  file: path=/opt/docker/mysql/conf.d state=directory recurse=yes

- name: configure mysql from template
  template: src=my.tpl dest=/opt/docker/mysql/conf.d/00-provision.cnf

- name: install container
  docker:
    name: "mysql"
    image: "mysql:{{docker_mysql_version}}"
    state: "{{docker_mysql_state}}"
    volumes:
      - "/opt/docker/mysql/data:/var/lib/mysql"
      - "/opt/docker/mysql/conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{docker_mysql_root_password}}"