---
- name: add ppa repository for php 7
  apt_repository: repo='ppa:ondrej/php-7.0' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install php
  apt: pkg={{item}} state=present
  with_items:
    - php
    - php-imagick
    - php-memcached
    - php-mysql
    - php-sqlite3
    - php-xdebug

- name: configure php5 apache2
  template: src=php/apache2.tpl dest=/etc/php/7.0/apache2/conf.d/00-provision.ini

- name: configure php5 cli
  template: src=php/cli.tpl dest=/etc/php/7.0/cli/conf.d/00-provision.ini

- name: remove default html folder
  file: path=/var/www/html state=absent

- name: configure apache2 modules
  apache2_module: state=present name={{item}}
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - proxy
    - proxy_http
  notify: webserver_restart_apache2

- name: create apache2 sites
  template: src=sites/{{item}}.conf dest=/etc/apache2/sites-available/{{item}}.conf
  with_items:
    - 000-default
    - 001-builds
    - 002-releases
    - 1000-dynamic-hosts

- name: enable apache2 sites
  command: a2ensite {{item}}
  args:
    creates: /etc/apache2/sites-enabled/{{item}}.conf
  with_items:
    - 000-default
    - 001-builds
    - 002-releases
    - 1000-dynamic-hosts
  notify: webserver_restart_apache2