---
- name: install container
  docker:
    name: "swagger_generator"
    image: "swaggerapi/swagger-generator:{{docker_swagger_generator_version}}"
    state: "{{docker_swagger_generator_state}}"
    ports:
      - "{{docker_swagger_generator_web_port}}:8080"

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-docker-swagger-generator.conf
  notify:
    - base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-docker-swagger-generator.conf creates=/etc/apache2/sites-enabled/100-docker-swagger-generator.conf
  notify:
    - base_apache2_restart