---
- name: create phing commons folder
  file: path=/opt/vagrant/phing-commons state=directory recurse=yes

- name: install
  unarchive: src=/vagrant/files/phing-commons/releases/phing-commons-9.2.0.tar.gz dest=/opt/vagrant/phing-commons creates=/opt/vagrant/phing-commons/VERSION

- name: install environment
  template: src=phing-commons.tpl dest=/etc/profile.d/phing-commons.sh



- name: install root users phing-commons folder
  file: path=/root/phing-commons state=directory recurse=yes

- stat: path=/vagrant/ansible/config/phing-commons/build.properties
  register: phing_commons_root_properties

- name: install defined root users build.properties from ansible config
  template: dest=/root/phing-commons/build.properties src=/vagrant/ansible/config/phing-commons/build.properties
  when: phing_commons_root_properties.stat.exists == true

- name: install default root users build.properties
  template: dest=/root/phing-commons/build.properties src=build.properties.tpl
  when: phing_commons_root_properties.stat.exists == false



- name: check if jenkins home directory exists
  stat: path=/var/lib/jenkins
  register: jenkins_home_directory

- stat: path=/vagrant/ansible/config/phing-commons/build.properties
  register: phing_commons_root_properties

- name: install jenkins users phing-commons folder
  file: path=/var/lib/jenkins/phing-commons state=directory recurse=yes owner=jenkins group=jenkins
  when: jenkins_home_directory.stat.exists == true

- name: install defined jenkins users build.properties from ansible config
  template: owner=jenkins group=jenkins dest=/var/lib/jenkins/phing-commons/build.properties src=/vagrant/ansible/config/phing-commons/build.properties
  when: jenkins_home_directory.stat.exists == true and phing_commons_root_properties.stat.exists == true

- name: install default jenkins users build.properties
  template: owner=jenkins group=jenkins dest=/var/lib/jenkins/phing-commons/build.properties src=build.properties
  when: jenkins_home_directory.stat.exists == true and phing_commons_root_properties.stat.exists == false