---
- name: install phing commons folder
  file: path=/opt/vagrant/phing-commons state=directory recurse=yes

- name: install
  command: tar xfz /vagrant/files/phing-commons/releases/phing-commons-8.11.0.tar.gz -C /opt/vagrant/phing-commons
  args:
    creates: /opt/vagrant/phing-commons/VERSION

- name: install on path
  template: src=phing-commons.sh dest=/etc/profile.d/phing-commons.sh

- name: install root users phing-commons folder
  file: path=/root/phing-commons state=directory recurse=yes

- stat: path=/vagrant/files/phing-commons/build.properties
  register: phing_commons_root_properties

- name: install default root users build.properties
  template: src=build.properties dest=/root/phing-commons/build.properties
  when: phing_commons_root_properties.stat.exists == False

- name: install defined root users build.properties
  template: src=/vagrant/files/phing-commons/build.properties dest=/root/phing-commons/build.properties
  when: phing_commons_root_properties.stat.exists == True