---
- name: install container
  docker:
    name: "elasticsearch"
    image: "elasticsearch:{{docker_elasticsearch_version}}"
    state: "{{docker_elasticsearch_state}}"
    ports:
      - "9200:9200"
      - "9300:9300"

- name: install container
  docker:
    name: "elasticsearch_kibana"
    image: "kibana:{{docker_elasticsearch_kibana_version}}"
    state: "{{docker_elasticsearch_kibana_state}}"
    ports:
      - "{{docker_elasticsearch_kibana_web_port}}:5601"
    env:
      ELASTICSEARCH_URL: "http://box.entwickl.de:9200"

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-docker-elasticsearch-kibana.conf
  notify:
    - base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-docker-elasticsearch-kibana.conf creates=/etc/apache2/sites-enabled/100-docker-elasticsearch-kibana.conf
  notify:
    - base_apache2_restart