---
- name: install packages
  apt: pkg={{item}} state=present
  with_items:
    - nullmailer

- name: create mailname
  template: src=etc/mailname.tpl dest=/etc/mailname

- name: create nullmailer remotes
  template: src=etc/nullmailer/remotes.tpl dest=/etc/nullmailer/remotes

- name: install container
  docker:
    name: mailcatcher
    image: schickling/mailcatcher
    state: started
    ports:
    - "1080:1080"
    - "1025:1025"

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-mailcatcher.conf

- name: enable apache2 sites
  command: a2ensite 100-mailcatcher
  args:
    creates: /etc/apache2/sites-enabled/1080-mailcatcher.conf
  notify: webserver_restart_apache2