---
- name: install container
  docker:
    name: mailcatcher
    image: schickling/mailcatcher:{{docker_mailcatcher_version}}
    state: started
    ports:
      - "1080:1080"
      - "1025:1025"

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-docker-mailcatcher.conf
  notify:
    - base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-docker-mailcatcher.conf creates=/etc/apache2/sites-enabled/100-docker-mailcatcher.conf
  notify:
    - base_apache2_restart