---
- name: install essential packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-7-jdk

- name: install public key
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: install repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: install
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - jenkins

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-ci-jenkins.conf
  notify: base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-ci-jenkins.conf
  args:
    creates: /etc/apache2/sites-enabled/100-ci-jenkins.conf
  notify: base_apache2_restart

- name: download current jenkins-cli.jar to install packages
  get_url: url=http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar dest=/tmp/jenkins-cli.jar

- name: install optional plugins
  command: java -jar /tmp/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{item}}
  args:
    creates: /var/lib/jenkins/plugins/{{item}}.jpi
  with_items:
    - thinBackup
    - configure-job-column-plugin
    - compact-columns
    - sectioned-view
    - timestamper
    - copyartifact
    - ansible
    - git
    - clover
    - checkstyle
    - cron_column
    - greenballs
    - bulk-builder
    - build-pipeline-plugin
    - phing
    - analysis-collector
    - extensible-choice-parameter
    - ws-cleanup
    - managed-scripts
    - publish-over-ssh