---
- name: install essential packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-7-jdk

- name: install public key
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: install repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: install
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - jenkins

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-ci-jenkins.conf
  notify:
    - base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-ci-jenkins.conf creates=/etc/apache2/sites-enabled/100-ci-jenkins.conf
  notify:
    - base_apache2_restart