---
- name: download current jenkins-cli.jar to install packages
  get_url: url=http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar dest=/tmp/jenkins-cli.jar

- name: install optional plugins
  command: java -jar /tmp/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{item}} creates=/var/lib/jenkins/plugins/{{item}}.jpi
  with_items:
    - thinBackup
    - configure-job-column-plugin
    - compact-columns
    - sectioned-view
    - timestamper
    - copyartifact
    - ansible
    - git
    - clover
    - checkstyle
    - cron_column
    - greenballs
    - bulk-builder
    - build-pipeline-plugin
    - phing
    - analysis-collector
    - extensible-choice-parameter
    - ws-cleanup
    - managed-scripts
    - publish-over-ssh
    - categorized-view
    - ez-templates
  notify:
    - base_jenkins_restart