---
- name: add ppa repository for php 5.6
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install php
  apt: pkg={{item}} state=present
  with_items:
    - nginx
    - php5-fpm

- name: configure php5 cli
  template: src=php/cli.tpl dest=/etc/php5/cli/conf.d/00-provision.ini

- name: configure php5 fpm
  template: src=php/fpm.tpl dest=/etc/php5/fpm/conf.d/00-provision.ini

- name: nginx configuration
  template: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf
  notify: webserver_restart_nginx

- name: create apache2 sites
  template: src=sites/{{item}}.conf dest=/etc/nginx/sites-enabled/{{item}}.conf
  with_items:
    - 000-default
    - 001-builds
    - 002-releases
    - 1000-dynamic-hosts
  notify: webserver_restart_nginx