---
- name: install php
  apt: pkg={{item}} state=present
  with_items:
    - php5
    - php5-apcu
    - php5-curl
    - php5-geoip
    - php5-imagick
    - php5-json
    - php5-memcached
    - php5-mongo
    - php5-mysql
    - php5-sqlite
    - php5-xdebug
    - php5-xsl

- name: install php mcrypt
  apt: pkg={{item}} state=present
  with_items:
    - php5-mcrypt
  notify:
    - webserver_php5enmod_mcrypt

- name: install php xhprof
  apt: pkg={{item}} state=present
  with_items:
    - php5-xhprof
  notify:
    - webserver_php5enmod_xhprof
    - webserver_php5enmod_xhprof_repair_cli
    - webserver_php5enmod_xhprof_repair_apache2

- name: configure php5 apache2
  template: src=php5/apache2.tpl dest=/etc/php5/apache2/conf.d/00-provision.ini

- name: configure php5 cli
  template: src=php5/cli.tpl dest=/etc/php5/cli/conf.d/00-provision.ini

- name: configure apache2 modules
  apache2_module: state=present name={{item}}
  with_items:
    - php5
    - rewrite
    - vhost_alias
    - proxy
    - proxy_http
    - headers
  notify: webserver_restart_apache2

- name: create apache2 sites
  template: src=sites/{{item}}.conf dest=/etc/apache2/sites-available/{{item}}.conf
  with_items:
    - 000-default
    - 001-builds
    - 002-releases
    - 1000-dynamic-hosts

- name: enable apache2 sites
  command: a2ensite {{item}}
  args:
    creates: /etc/apache2/sites-enabled/{{item}}.conf
  with_items:
    - 000-default
    - 001-builds
    - 002-releases
    - 1000-dynamic-hosts
  notify: webserver_restart_apache2