---
- name: create volume directory for container
  file: path=/opt/docker/neo4j/data state=directory recurse=yes

- name: install container
  docker:
    name: "neo4j"
    image: "neo4j:{{docker_neo4j_version}}"
    state: "{{docker_neo4j_state}}"
    volumes:
    - "/opt/docker/neo4j/data:/data"
    ports:
      - "7473:7473"
      - "{{docker_neo4j_web_port}}:7474"

- name: create apache2 sites
  template: src=vhost.conf dest=/etc/apache2/sites-available/100-docker-neo4j.conf
  notify:
    - base_apache2_restart

- name: enable apache2 sites
  command: a2ensite 100-docker-neo4j.conf creates=/etc/apache2/sites-enabled/100-docker-neo4j.conf
  notify:
    - base_apache2_restart