---
- name: install container
  docker:
    name: grafana
    image: grafana/grafana
    state: started
    ports:
    - "49152:3000"
    env:
      GF_SECURITY_ADMIN_PASSWORD: welcome

- name: create apache2 site
  template: src=vhost.tpl dest=/etc/apache2/sites-available/49152-grafana.conf

- name: enable apache2 sites
  command: a2ensite 49152-grafana
  args:
    creates: /etc/apache2/sites-enabled/49152-grafana.conf

- name: restart apache2
  service: name=apache2 enabled=yes state=restarted