---
- name: install public key
  apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: create list file
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install essential packages
  apt: pkg={{item}} state=present
  with_items:
    - python-pip

- name: install docker-py
  pip: name=docker-py

- name: install docker-engine
  apt: pkg={{item}} state=present
  with_items:
    - docker-engine