---
- hosts: all

  vars_files:
    - ../vagrant.yml

  roles:
    - role: elnebuloso.server-base
      tags:
        - system

    - role: geerlingguy.ntp
      tags:
        - system

    - role: tersmitten.locales
      tags:
        - system

    - role: elnebuloso.php7
      tags:
        - php

    - role: geerlingguy.composer
      tags:
        - php

    - role: elnebuloso.git
      tags:
        - ci

    - role: elnebuloso.subversion
      tags:
        - ci

    - role: elnebuloso.optipng
      tags:
        - ci

    - role: elnebuloso.jpegoptim
      tags:
        - ci

    - role: elnebuloso.yui-compressor
      tags:
        - ci

    - role: elnebuloso.closure-compiler
      tags:
        - ci

    - role: elnebuloso.compass
      tags:
        - ci

    - role: geerlingguy.nodejs
      tags:
        - nodejs

    - role: ocha.yarn
      tags:
        - nodejs

    - role: elnebuloso.docker
      tags:
        - docker

    - role: elnebuloso.docker
      tags:
        - docker

    - role: elnebuloso.docker-memcached
      tags:
        - docker

    - role: elnebuloso.docker-mysql
      tags:
        - docker

    - role: elnebuloso.docker-portainer
      tags:
        - docker

    - role: elnebuloso.docker-swagger-editor
      tags:
        - docker

    - role: elnebuloso.docker-swagger-generator
      tags:
        - docker