---
- hosts: all

  vars_files:
    - vars/all.yml

  roles:
    # system roles
    - {role: elnebuloso.server-base, tags: ['system']}
    - {role: geerlingguy.ntp, tags: ['system', 'system.ntp']}

    # php based roles
    - {role: elnebuloso.php71, tags: ['php']}
    - {role: geerlingguy.composer, tags: ['php', 'php.composer', 'php.phing']}
    - {role: elnebuloso.ci-phing-commons, tags: ['php', 'ci.composer', 'php.phing']}

    # ci based roles
    - {role: elnebuloso.ci, tags: ['ci', 'ci.base']}
    - {role: elnebuloso.ci-vcs, tags: ['ci', 'ci.vcs']}
    - {role: elnebuloso.ci-compass, tags: ['ci', 'ci.compass']}
    - {role: geerlingguy.nodejs, tags: ['ci', 'ci.nodejs']}
    - {role: ocha.yarn, tags: ['ci', 'ci.yarn']}

    # docker based roles
    - {role: angstwad.docker_ubuntu, tags: ['docker']}
    # - {role: elnebuloso.docker-mysql, tags: ['docker', 'docker.mysql']}
    # - {role: elnebuloso.docker-memcached, tags: ['docker', 'docker.memcached']}
    # - {role: elnebuloso.docker-swagger-editor, tags: ['docker', 'docker.swagger', 'docker.swagger.editor']}
    # - {role: elnebuloso.docker-swagger-generator, tags: ['docker', 'docker.swagger', 'docker.swagger.generator']}