---
- src: elnebuloso.server-base
- src: elnebuloso.php70
- src: elnebuloso.ci
- src: elnebuloso.ci-vcs
- src: elnebuloso.ci-compass
- src: elnebuloso.ci-phing-commons
- src: elnebuloso.docker
- src: elnebuloso.docker-mysql
- src: elnebuloso.docker-memcached
- src: elnebuloso.docker-swagger-editor
- src: elnebuloso.docker-swagger-generator

- src: geerlingguy.composer
  version: 1.5.0

- src: carlosbuenosvinos.ansistrano-deploy
  version: 1.11.0

- src: carlosbuenosvinos.ansistrano-rollback
  version: 1.5.0