---
- hosts: all

  vars_files:
    - ../vagrant.yml

  roles:
    - role: elnebuloso.package-upgrade
    - role: elnebuloso.server-base
    - role: geerlingguy.ntp
    - role: tersmitten.locales

    - role: elnebuloso.php7
    - role: geerlingguy.composer

    - role: elnebuloso.git
    - role: elnebuloso.subversion
    - role: elnebuloso.optipng
    - role: elnebuloso.jpegoptim
    - role: elnebuloso.yui-compressor
    - role: elnebuloso.closure-compiler
    - role: elnebuloso.compass
    - role: geerlingguy.nodejs
    - role: ocha.yarn

    - role: elnebuloso.docker
    - role: elnebuloso.docker-compose
    - role: elnebuloso.docker-pip
    - role: elnebuloso.docker-memcached
    - role: elnebuloso.docker-mysql
    - role: elnebuloso.docker-portainer
    - role: elnebuloso.docker-swagger-editor
    - role: elnebuloso.docker-swagger-generator

    - role: elnebuloso.package-cleanup