---
- hosts: all
  vars_files:
    - /vagrant/box.yml
  roles:
    - {role: essentials,               tags: ["full", "base"]}
    - {role: vcs,                      tags: ["full", "base"]}
    - {role: apache2-php5,             tags: ["full", "base"]}

    - {role: docker,                   tags: ["full", "base"]}
    - {role: docker-ansible-semaphore, tags: ["full", "docker-ansible-semaphore"]}
    - {role: docker-grafana,           tags: ["full", "docker-grafana"]}
    - {role: docker-graphite-statsd,   tags: ["full", "docker-graphite-statsd"]}
    - {role: docker-mailcatcher,       tags: ["full", "docker-mailcatcher"]}
    - {role: docker-memcached,         tags: ["full", "docker-memcached"]}
    - {role: docker-mongo,             tags: ["full", "docker-mongo"]}
    - {role: docker-mysql,             tags: ["full", "docker-mysql"]}

    - {role: composer,                 tags: ["full", "base"]}
    - {role: composer-phing-commons,   tags: ["full", "composer-phing-commons"]}

    - {role: ci,                       tags: ["full", "base"]}
    - {role: ci-compass,               tags: ["full", "ci-compass"]}

    - {role: nodejs,                   tags: ["full", "base"]}
    - {role: nodejs-npm-bower,         tags: ["full", "nodejs-npm-bower"]}
    - {role: nodejs-npm-grunt,         tags: ["full", "nodejs-npm-grunt"]}