---
- hosts: all

  vars_files:
    - vars/all.yml

  roles:
    - {role: elnebuloso.server-base}
    - {role: elnebuloso.php56-apache2}
    # - {role: elnebuloso.docker}
    # - {role: elnebuloso.docker-mysql}
    # - {role: elnebuloso.ci-jenkins}