---
- hosts: all

  vars_files:
    - vars/all.yml

  roles:
    - {role: elnebuloso.server-base}
    - {role: elnebuloso.php56-apache2}
    - {role: elnebuloso.ci}
    - {role: elnebuloso.ci-vcs}
    - {role: elnebuloso.ci-compass}
    - {role: elnebuloso.ci-jenkins}
    - {role: elnebuloso.ci-phing-commons}
    # - {role: elnebuloso.docker}
    # - {role: elnebuloso.docker-mysql}
    # - {role: elnebuloso.docker-memcached}
    # - {role: elnebuloso.docker-swagger-editor}
    # - {role: elnebuloso.docker-swagger-generator}