---
- hosts: all

  vars_files:
    - vars/all.yml

  tasks:
    - name: download current jenkins-cli.jar to install packages
      get_url: url=http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar dest=/tmp/jenkins-cli.jar

    - name: install optional plugins
      command: java -jar /tmp/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{item}} creates=/var/lib/jenkins/plugins/{{item}}.jpi
      with_items: "{{ci_jenkins_plugins}}"
      notify:
        - base_jenkins_restart