---
- hosts: all
  vars_files:
    - vars/all.yml
  roles:
    - essentials
    - apache2-php5
    - docker
    - docker-mysql
    - docker-memcached
    - docker-mongo
    - docker-grafana
    - docker-graphite-statsd
    - docker-ansible-semaphore
    - docker-mailcatcher
    - docker-elasticsearch
    - vcs
    - composer
    - ci