---
- hosts: all

  vars_files:
    - vars/all.yml

  roles:
    - {role: base}
    - {role: elnebuloso.server-base}

    # php based roles
    - {role: elnebuloso.php70, when: enable_php70 == true}
    - {role: geerlingguy.composer, when: enable_composer == true}

    # ci based roles
    - {role: elnebuloso.ci, when: enable_ci == true}
    - {role: elnebuloso.ci-vcs, when: enable_ci_vcs == true}
    - {role: elnebuloso.ci-compass, when: enable_ci_compass == true}
    - {role: elnebuloso.ci-phing-commons, when: enable_ci == true and enable_ci_vcs == true and enable_ci_phing_commons == true}

    # docker based roles
    - {role: elnebuloso.docker, when: enable_docker == true}
    - {role: elnebuloso.docker-mysql, when: enable_docker == true and enable_docker_mysql == true}
    - {role: elnebuloso.docker-memcached, when: enable_docker == true and enable_docker_memcached == true}
    - {role: elnebuloso.docker-swagger-editor, when: enable_docker == true and enable_docker_swagger_editor == true}
    - {role: elnebuloso.docker-swagger-generator, when: enable_docker == true and enable_docker_swagger_generator == true}