---
- name: install
  script: composer.sh creates=/usr/bin/composer

- name: setting composer environment
  template: src=composer-env.tpl dest=/etc/profile.d/composer-env.sh
  register: composer_environment_update

- name: register github_oauth_token for root user
  command: composer config -g github-oauth.github.com {{github_oauth_token}}
  when: composer_environment_update.changed == true



- name: check if jenkins home directory exists
  stat: path=/var/lib/jenkins
  register: jenkins_home_directory

- name: register github_oauth_token for jenkins user
  command: composer config -g github-oauth.github.com {{github_oauth_token}}
  become: yes
  become_method: sudo
  become_user: jenkins
  when: composer_environment_update.changed == true and jenkins_home_directory.stat.exists == true