---
- name: install
  script: composer.sh creates=/usr/bin/composer

- name: setting composer environment
  template: src=composer-env.tpl dest=/etc/profile.d/composer-env.sh

- name: register github_oauth_token for root user
  command: composer config -g github-oauth.github.com {{github_oauth_token}}

- name: register github_oauth_token for jenkins user
  command: composer config -g github-oauth.github.com {{github_oauth_token}}
  become: yes
  become_method: sudo
  become_user: jenkins
  when: ci_jenkins_installed == true